Repository bdiptesh/CodeLib, pull requests merged in 2022-01, with the labels that each got.

#23 feature_22_testing
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/ISSUE_TEMPLATE/feature_request.yaml
  .github/ISSUE_TEMPLATE/maintenance_request.yaml
  .github/workflows/checks.yml
  bin/metrics/build/lib.linux-x86_64-3.7/metrics.cpython-37m-x86_64-linux-gnu.so
  bin/metrics/build/temp.linux-x86_64-3.7/metrics.o
  bin/metrics/metrics.c
  bin/metrics/metrics.pyx
  bin/metrics/metrics.so
  bin/run_tests.sh
  data/input/test_time_series.csv
  data/input/test_time_series.xlsx
  data/input/test_ts_passengers.csv
  logs/cov.out
  logs/pip.out
  logs/pylint/lib-timeseries-py.out
  logs/pylint/tests-test_metrics-py.out
  mllib/__main__.py
  mllib/lib/metrics.so
  mllib/lib/timeseries.py
  requirements.txt
  tests/test_cluster.py
  tests/test_knn.py
  tests/test_metrics.py
  tests/test_model.py
  tests/test_timeseries.py
  tests/test_tree.py
Labels: 1: stat, 2: merge

#25 bug_24_testing
  data/input/test_time_series.xlsx
  logs/cov.out
  logs/pylint/lib-timeseries-py.out
  mllib/lib/timeseries.py
  requirements.txt
  tests/test_timeseries.py
Labels: 1: stat, 2: merge

#32 feature_maintenance_26_27_28_29_31_testing
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/ISSUE_TEMPLATE/eda_request.yaml
  .github/ISSUE_TEMPLATE/feature_request.yaml
  .github/ISSUE_TEMPLATE/maintenance_request.yaml
  .github/ISSUE_TEMPLATE/user_story.yaml
  .github/workflows/checks.yml
  bin/metrics/build/lib.linux-x86_64-3.7/metrics.cpython-37m-x86_64-linux-gnu.so
  bin/metrics/build/temp.linux-x86_64-3.7/metrics.o
  bin/metrics/metrics.c
  bin/metrics/metrics.pyx
  bin/metrics/metrics.so
  bin/run_tests.sh
  logs/cov.out
  logs/pylint/lib-timeseries-py.out
  logs/pylint/lib-tree-py.out
  mllib/__main__.py
  mllib/lib/cfg.py
  mllib/lib/metrics.so
  mllib/lib/timeseries.py
  mllib/lib/tree.py
  requirements.txt
  tests/test_metrics.py
  tests/test_timeseries.py
  tests/test_tree.py
Labels: 1: merge

#35 maintenance_34_testing
  README.md
  logs/cov.out
  logs/pylint/lib-__init__-py.out
  logs/pylint/lib-knn-py.out
  logs/pylint/lib-model-py.out
  logs/pylint/lib-timeseries-py.out
  logs/pylint/lib-tree-py.out
  logs/pylint/mllib-__init__-py.out
  logs/pylint/tests-test_metrics-py.out
  mllib/__init__.py
  mllib/lib/__init__.py
  mllib/lib/knn.py
  mllib/lib/model.py
  mllib/lib/opt.py
  requirements.txt
  tests/test_model.py
  tests/test_timeseries.py
  tests/test_tree.py
Labels: 1: merge

#39 maintenance_38_testing
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/ISSUE_TEMPLATE/eda_request.yaml
  .github/ISSUE_TEMPLATE/feature_request.yaml
  .github/ISSUE_TEMPLATE/maintenance_request.yaml
  .github/ISSUE_TEMPLATE/user_story.yaml
  .github/PULL_REQUEST_TEMPLATE.md
Labels: merge
